# Generated by Django 3.2.8 on 2021-11-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'exam_category',
            },
        ),
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('adress', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'exam_deliver',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('description', models.TextField()),
                ('barcode', models.CharField(max_length=100)),
                ('categoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.category')),
            ],
            options={
                'db_table': 'exam_product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=10, max_digits=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('deliver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.deliver')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exam.product')),
            ],
        ),
    ]
