# Generated by Django 3.2.9 on 2021-11-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='exam_category',
        ),
        migrations.AlterModelTable(
            name='deliver',
            table='exam_deliver',
        ),
        migrations.AlterModelTable(
            name='order',
            table='exam_order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='exam_product',
        ),
    ]
