# Generated by Django 3.2.9 on 2021-11-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20211107_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_name',
        ),
    ]
